version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    mix:
      actions:
        patterns:
          - "*"
