styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
  - config
  - priv/repo
  - test
  - assets/vendor
  - assets/css/vendor
  - assets/webpack.config.js
