alias Hexpm.Repo
alias Hexpm.{
  Accounts.AuditLog,
  Accounts.Email,
  Accounts.Key,
  Accounts.Keys,
  Accounts.Session,
  Accounts.User,
  Accounts.UserHandles,
  Accounts.Users,
  Emails,
  Emails.Mailer,
  Repository.Assets,
  Repository.Download,
  Repository.Install,
  Repository.Installs,
  Repository.Owners,
  Repository.Package,
  Repository.PackageDownload,
  Repository.PackageMetadata,
  Repository.PackageOwner,
  Repository.Packages,
  Repository.RegistryBuilder,
  Repository.Release,
  Repository.ReleaseDownload,
  Repository.ReleaseMetadata,
  Repository.ReleaseRetirement,
  Repository.Releases,
  Repository.Repositories,
  Repository.Repository,
  Repository.RepositoryUser,
  Repository.Requirement,
  Repository.Resolver,
  Repository.Sitemaps,
}

import_if_available Ecto.Query, only: [from: 1, from: 2]
