FORMAT: 1A

# hex
The Hex API is based on REST, it is currently in beta and so can change at any time.

## Related specifications

* Tarball format - ...
* Registry format - ...

# Group Packages
Something about packages.

## Packages Collection [/packages{?sort}]
### List all Packages [GET]

+ Parameters
    + sort: downloads (enum[string], optional)
        + Default: name
        + Members
            + name
            + downloads
            + inserted_at
            + updated_at

+ Request
    + Header

            Accept: application/json

+ Response 200 (application/json)
    + Body

            [{
              "name": "plug",
              "url": "https://hex.pm/api/packages/plug",
              "meta": {
                "links": {"GitHub": "https://github.com/elixir-lang/plug"},
                "licenses": ["Apache 2"],
                "description": "A specification and conveniences for composable modules in between web applications"
              },
              "downloads": {
                "all": 43,
                "week": 14,
                "day": 2
              },
              "releases": {
                "version": "0.4.1",
                "url": "https://hex.pm/api/packages/plug/releases/0.4.1",
                "inserted_at": "2014-04-23T18:58:54Z",
                "updated_at": "2015-04-26T15:26:23Z"
              },
              "inserted_at": "2015-03-24T20:31:35Z",
              "updated_at": "2015-04-02T04:55:41Z"
            }]

