defmodule Mix.Tasks.GenerateLumisCss do
  @moduledoc """
  Generates assets/vendor/css/lumis.css from Lumis github_light and github_dark themes.

  Usage:
      mix generate_lumis_css
  """
  use Mix.Task

  @output_path "assets/vendor/css/lumis.css"
  @light_theme "github_light"
  @dark_theme "github_dark"

  # Override theme backgrounds to match the hex.pm design
  @light_bg "rgb(246, 248, 250)"
  @dark_bg "var(--color-grey-900)"

  @impl Mix.Task
  def run(_args) do
    File.mkdir_p!(Path.dirname(@output_path))

    css = """
    /* Generated by mix generate_lumis_css — do not edit manually */
    /* Themes: #{@light_theme} (light) / #{@dark_theme} (dark) */

    #{theme_css(@light_theme, "", @light_bg)}
    #{theme_css(@dark_theme, ~s(html[data-theme="dark"]), @dark_bg)}
    """

    File.write!(@output_path, css)
    Mix.shell().info("Written #{@output_path}")
  end

  defp theme_css(theme, scope, background) do
    Lumis.Theme.build_css!(
      theme,
      scope: scope,
      container_style: [
        {"background-color", background},
        {"border-radius", "0.375rem"},
        {"padding", "1rem"}
      ]
    )
  end
end
