defmodule Mix.Tasks.GenerateLumisCss do
  @moduledoc """
  Generates assets/vendor/css/lumis.css from Lumis github_light and github_dark themes.

  Usage:
      mix generate_lumis_css
  """
  use Mix.Task

  @output_path "assets/vendor/css/lumis.css"
  @light_theme "github_light"
  @dark_theme "github_dark"

  # Override theme backgrounds to match the hex.pm design
  @light_bg "rgb(246, 248, 250)"
  @dark_bg "var(--color-grey-900)"

  @impl Mix.Task
  def run(_args) do
    File.mkdir_p!(Path.dirname(@output_path))
    light = Lumis.Native.get_theme(@light_theme)
    dark = Lumis.Native.get_theme(@dark_theme)

    css = """
    /* Generated by mix generate_lumis_css — do not edit manually */
    /* Themes: #{@light_theme} (light) / #{@dark_theme} (dark) */

    #{base_rules(light, "", @light_bg)}

    #{token_rules(light, "")}

    #{base_rules(dark, "html[data-theme=\"dark\"] ", @dark_bg)}

    #{token_rules(dark, "html[data-theme=\"dark\"] ")}
    """

    File.write!(@output_path, css)
    Mix.shell().info("Written #{@output_path}")
  end

  defp base_rules(theme, prefix, bg_override) do
    normal = theme.highlights["normal"]

    if normal do
      bg = bg_override || normal.bg || "transparent"

      """
      #{prefix}.lumis {
        background: #{bg};
        color: #{normal.fg || "inherit"};
        border-radius: 0.375rem;
        padding: 1rem;
        overflow-x: auto;
      }
      """
    else
      ""
    end
  end

  defp token_rules(theme, prefix) do
    theme.highlights
    |> Enum.reject(fn {name, _} -> name == "normal" end)
    |> Enum.sort_by(fn {name, _} -> name end)
    |> Enum.map_join("\n", fn {token, style} ->
      class = String.replace(token, ".", "-")
      rules = style_to_rules(style)

      if rules == [] do
        nil
      else
        """
        #{prefix}.lumis .#{class} {
        #{Enum.map_join(rules, "\n", fn r -> "  #{r}" end)}
        }
        """
      end
    end)
    |> String.replace(~r/\n{3,}/, "\n\n")
  end

  defp style_to_rules(%Lumis.Theme.Style{} = s) do
    []
    |> maybe_add("color", s.fg)
    |> maybe_add("background", s.bg)
    |> then(fn r -> if s.bold, do: r ++ ["font-weight: bold;"], else: r end)
    |> then(fn r -> if s.italic, do: r ++ ["font-style: italic;"], else: r end)
    |> then(fn r ->
      decorations =
        []
        |> then(fn d ->
          if s.text_decoration.underline, do: d ++ ["underline"], else: d
        end)
        |> then(fn d ->
          if s.text_decoration.strikethrough, do: d ++ ["line-through"], else: d
        end)

      if decorations != [],
        do: r ++ ["text-decoration: #{Enum.join(decorations, " ")};"],
        else: r
    end)
  end

  defp maybe_add(rules, _prop, nil), do: rules
  defp maybe_add(rules, prop, value), do: rules ++ ["#{prop}: #{value};"]
end
